// Generated by scripts/generate-trust-web-signals.mjs
// Derived from live vendor websites.

export interface WebTrustSignals {
  sourceUrl: string;
  checkedAt: string;
  statusCode?: number;
  fetchError?: string;
  signalCount: number;
  signals: {
    privacy: boolean;
    openSourceMention: boolean;
    encryption: boolean;
    selfHosting: boolean;
    audit: boolean;
    noLogs: boolean;
  };
}

export const trustWebSignalsById: Record<string, WebTrustSignals> = {
  "adyen": {
    "sourceUrl": "https://www.adyen.com",
    "checkedAt": "2026-02-10T21:53:44.727Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "airvpn": {
    "sourceUrl": "https://airvpn.org",
    "checkedAt": "2026-02-10T21:53:45.109Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "bitwarden": {
    "sourceUrl": "https://bitwarden.com",
    "checkedAt": "2026-02-10T21:53:45.414Z",
    "statusCode": 200,
    "signalCount": 4,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "black-forest-labs": {
    "sourceUrl": "https://bfl.ai",
    "checkedAt": "2026-02-10T21:53:45.672Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "collabora-online": {
    "sourceUrl": "https://www.collaboraonline.com",
    "checkedAt": "2026-02-10T21:53:45.884Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "cryptpad": {
    "sourceUrl": "https://cryptpad.org",
    "checkedAt": "2026-02-10T21:53:46.195Z",
    "statusCode": 200,
    "signalCount": 6,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": true,
      "audit": true,
      "noLogs": true
    }
  },
  "deepl": {
    "sourceUrl": "https://www.deepl.com",
    "checkedAt": "2026-02-10T21:53:46.519Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "diaspora": {
    "sourceUrl": "https://diasporafoundation.org",
    "checkedAt": "2026-02-10T21:53:47.126Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "disroot": {
    "sourceUrl": "https://disroot.org",
    "checkedAt": "2026-02-10T21:53:47.337Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "ecosia": {
    "sourceUrl": "https://www.ecosia.org",
    "checkedAt": "2026-02-10T21:53:47.735Z",
    "statusCode": 403,
    "fetchError": "HTTP 403",
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "element": {
    "sourceUrl": "https://element.io",
    "checkedAt": "2026-02-10T21:53:47.955Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "euria": {
    "sourceUrl": "https://euria.infomaniak.com",
    "checkedAt": "2026-02-10T21:53:48.257Z",
    "statusCode": 200,
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "filen": {
    "sourceUrl": "https://filen.io",
    "checkedAt": "2026-02-10T21:53:48.502Z",
    "statusCode": 200,
    "signalCount": 4,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "friendica": {
    "sourceUrl": "https://friendi.ca",
    "checkedAt": "2026-02-10T21:53:48.796Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "hetzner": {
    "sourceUrl": "https://www.hetzner.com",
    "checkedAt": "2026-02-10T21:53:49.123Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "hostinger": {
    "sourceUrl": "https://www.hostinger.com",
    "checkedAt": "2026-02-10T21:53:49.371Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "hugging-face": {
    "sourceUrl": "https://huggingface.co",
    "checkedAt": "2026-02-10T21:53:49.643Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "infomaniak": {
    "sourceUrl": "https://www.infomaniak.com",
    "checkedAt": "2026-02-10T21:53:49.830Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "ionos": {
    "sourceUrl": "https://www.ionos.com",
    "checkedAt": "2026-02-10T21:53:50.566Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "ivpn": {
    "sourceUrl": "https://www.ivpn.net",
    "checkedAt": "2026-02-10T21:53:51.518Z",
    "statusCode": 200,
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "kdrive": {
    "sourceUrl": "https://www.infomaniak.com/en/ksuite/kdrive",
    "checkedAt": "2026-02-10T21:53:52.109Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "keepassxc": {
    "sourceUrl": "https://keepassxc.org",
    "checkedAt": "2026-02-10T21:53:52.653Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "lemmy": {
    "sourceUrl": "https://join-lemmy.org",
    "checkedAt": "2026-02-10T21:53:52.908Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": false,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "libreoffice": {
    "sourceUrl": "https://www.libreoffice.org",
    "checkedAt": "2026-02-10T21:53:53.192Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "lumo": {
    "sourceUrl": "https://lumo.proton.me",
    "checkedAt": "2026-02-10T21:53:53.511Z",
    "statusCode": 200,
    "signalCount": 4,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": true
    }
  },
  "magic-earth": {
    "sourceUrl": "https://www.magicearth.com",
    "checkedAt": "2026-02-10T21:53:53.724Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "mailbox-org": {
    "sourceUrl": "https://mailbox.org",
    "checkedAt": "2026-02-10T21:53:54.228Z",
    "statusCode": 200,
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "mailfence": {
    "sourceUrl": "https://mailfence.com",
    "checkedAt": "2026-02-10T21:53:54.576Z",
    "statusCode": 500,
    "fetchError": "HTTP 500",
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "mastodon": {
    "sourceUrl": "https://joinmastodon.org",
    "checkedAt": "2026-02-10T21:53:54.844Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "matomo": {
    "sourceUrl": "https://matomo.org",
    "checkedAt": "2026-02-10T21:53:55.054Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "mistral": {
    "sourceUrl": "https://mistral.ai",
    "checkedAt": "2026-02-10T21:53:55.310Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "mollie": {
    "sourceUrl": "https://www.mollie.com",
    "checkedAt": "2026-02-10T21:53:55.703Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "mullvad-browser": {
    "sourceUrl": "https://mullvad.net/en/browser",
    "checkedAt": "2026-02-10T21:53:56.014Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "mullvad-vpn": {
    "sourceUrl": "https://mullvad.net",
    "checkedAt": "2026-02-10T21:53:56.299Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "nextcloud": {
    "sourceUrl": "https://nextcloud.com",
    "checkedAt": "2026-02-10T21:53:56.597Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "nordvpn": {
    "sourceUrl": "https://nordvpn.com",
    "checkedAt": "2026-02-10T21:53:56.855Z",
    "statusCode": 403,
    "fetchError": "HTTP 403",
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "ollama": {
    "sourceUrl": "https://ollama.com",
    "checkedAt": "2026-02-10T21:53:57.098Z",
    "statusCode": 200,
    "signalCount": 1,
    "signals": {
      "privacy": false,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "onlyoffice": {
    "sourceUrl": "https://www.onlyoffice.com",
    "checkedAt": "2026-02-10T21:53:57.424Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "openproject": {
    "sourceUrl": "https://www.openproject.org",
    "checkedAt": "2026-02-10T21:53:57.678Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "organic-maps": {
    "sourceUrl": "https://organicmaps.app",
    "checkedAt": "2026-02-10T21:53:57.947Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "osmand": {
    "sourceUrl": "https://osmand.net",
    "checkedAt": "2026-02-10T21:53:58.199Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "ovhcloud": {
    "sourceUrl": "https://www.ovhcloud.com",
    "checkedAt": "2026-02-10T21:53:58.427Z",
    "fetchError": "fetch failed",
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "passbolt": {
    "sourceUrl": "https://www.passbolt.com",
    "checkedAt": "2026-02-10T21:53:58.710Z",
    "statusCode": 200,
    "signalCount": 5,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": true,
      "audit": true,
      "noLogs": false
    }
  },
  "pcloud": {
    "sourceUrl": "https://www.pcloud.com",
    "checkedAt": "2026-02-10T21:53:59.018Z",
    "statusCode": 200,
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "peertube": {
    "sourceUrl": "https://joinpeertube.org",
    "checkedAt": "2026-02-10T21:53:59.226Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": false,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "pirsch": {
    "sourceUrl": "https://pirsch.io",
    "checkedAt": "2026-02-10T21:53:59.515Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "pixelfed": {
    "sourceUrl": "https://pixelfed.org",
    "checkedAt": "2026-02-10T21:53:59.735Z",
    "statusCode": 200,
    "signalCount": 0,
    "signals": {
      "privacy": false,
      "openSourceMention": false,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "plausible": {
    "sourceUrl": "https://plausible.io",
    "checkedAt": "2026-02-10T21:54:00.050Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "posteo": {
    "sourceUrl": "https://posteo.de",
    "checkedAt": "2026-02-10T21:54:00.272Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "prestashop": {
    "sourceUrl": "https://prestashop.com",
    "checkedAt": "2026-02-10T21:54:00.597Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "proton-drive": {
    "sourceUrl": "https://proton.me/drive",
    "checkedAt": "2026-02-10T21:54:01.246Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "proton-mail": {
    "sourceUrl": "https://proton.me/mail",
    "checkedAt": "2026-02-10T21:54:01.558Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "proton-pass": {
    "sourceUrl": "https://proton.me/pass",
    "checkedAt": "2026-02-10T21:54:01.749Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "proton-vpn": {
    "sourceUrl": "https://protonvpn.com",
    "checkedAt": "2026-02-10T21:54:01.955Z",
    "statusCode": 200,
    "signalCount": 5,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": true,
      "noLogs": true
    }
  },
  "saleor": {
    "sourceUrl": "https://saleor.io",
    "checkedAt": "2026-02-10T21:54:02.328Z",
    "statusCode": 200,
    "signalCount": 4,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "scaleway": {
    "sourceUrl": "https://www.scaleway.com",
    "checkedAt": "2026-02-10T21:54:03.092Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "shopware": {
    "sourceUrl": "https://www.shopware.com",
    "checkedAt": "2026-02-10T21:54:03.441Z",
    "statusCode": 200,
    "signalCount": 4,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": true,
      "noLogs": false
    }
  },
  "simple-analytics": {
    "sourceUrl": "https://www.simpleanalytics.com",
    "checkedAt": "2026-02-10T21:54:04.026Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "stability-ai": {
    "sourceUrl": "https://stability.ai",
    "checkedAt": "2026-02-10T21:54:04.435Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "startmail": {
    "sourceUrl": "https://www.startmail.com",
    "checkedAt": "2026-02-10T21:54:04.709Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "startpage": {
    "sourceUrl": "https://www.startpage.com",
    "checkedAt": "2026-02-10T21:54:05.010Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "taiga": {
    "sourceUrl": "https://taiga.io",
    "checkedAt": "2026-02-10T21:54:05.351Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "threema": {
    "sourceUrl": "https://threema.ch",
    "checkedAt": "2026-02-10T21:54:05.841Z",
    "statusCode": 200,
    "signalCount": 4,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "tresorit": {
    "sourceUrl": "https://tresorit.com",
    "checkedAt": "2026-02-10T21:54:06.293Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "tuta": {
    "sourceUrl": "https://tuta.com",
    "checkedAt": "2026-02-10T21:54:06.536Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  },
  "vikunja": {
    "sourceUrl": "https://vikunja.io",
    "checkedAt": "2026-02-10T21:54:06.826Z",
    "statusCode": 200,
    "signalCount": 3,
    "signals": {
      "privacy": true,
      "openSourceMention": true,
      "encryption": false,
      "selfHosting": true,
      "audit": false,
      "noLogs": false
    }
  },
  "vivaldi": {
    "sourceUrl": "https://vivaldi.com",
    "checkedAt": "2026-02-10T21:54:07.073Z",
    "statusCode": 200,
    "signalCount": 2,
    "signals": {
      "privacy": true,
      "openSourceMention": false,
      "encryption": true,
      "selfHosting": false,
      "audit": false,
      "noLogs": false
    }
  }
};
